RestaurantManagement/src/objects/Bill__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TableNumber__c</fullName>
        <label>TableNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Bill</label>
    <nameField>
        <label>Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/BIll__c.object
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>

RestaurantManagement/src/objects/BIll_Item__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>BIll Item</label>
    <nameField>
        <label>BIll Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Food_Quality__c</fullName>
        <label>Food Quality</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FB-{0000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Food_Item__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Whether the food item should be enabled in the menu or not</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enabled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Disbaled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of food - Veg, Non-Veg or Vegan</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Vegetarian</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Vegetarian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vegan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Food Item</label>
    <nameField>
        <label>Food Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Food_Order__c.object
<CustomObject>
    <fields>
        <fullName>DeliveryTime__c</fullName>
        <label>Delivery Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrderDateTime__c</fullName>
        <label>Order Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OrderId__c</fullName>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>PriceEstimate__c</fullName>
        <description>This will contain the Order Price + Tax amount
i.e. the summation of the prices of all the items in the order plus the tax applied.</description>
        <inlineHelpText>Order items price summation + Tax.</inlineHelpText>
        <label>Price Estimate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>This will contain the order price i.e. the summation of the prices of all the items in the order.</description>
        <inlineHelpText>Order items price summation.</inlineHelpText>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TableNumber__c</fullName>
        <label>Table Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TaxEstimate__c</fullName>
        <description>This field will contain the estimated tax on the price of the placed order.</description>
        <inlineHelpText>Tax on placed order as well as the cart.</inlineHelpText>
        <label>Tax Estimate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <description>This field will contain the tax of the items in the placed order.</description>
        <inlineHelpText>Tax on Placed Order</inlineHelpText>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalPriceEstimate__c</fullName>
        <description>This field will contain the summation of the total price of all the order items in this order. This is the expected bill to customer if all his cart items are accepted i.e. delivered.</description>
        <inlineHelpText>This is Expected Bill Amount to charge Customer if all order items are fulfilled.</inlineHelpText>
        <label>Total Price Estimate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <description>This field will contain the summation of the total price of all the order items which have status accepted and forward in this order, so that the customer is charged for the accepted order items only.</description>
        <inlineHelpText>This is Bill Amount to charge Customer.</inlineHelpText>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Food Order</label>
    <nameField>
        <label>Food Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Order_Item__c.object
<CustomObject>
    <description>The food items ordered by the customer.</description>
    <fields>
        <fullName>Delete_Status__c</fullName>
        <description>Used if the order item is deleted by the customer</description>
        <label>Delete Status</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Food_Item__c</fullName>
        <description>The food item ordered</description>
        <label>Food Item</label>
        <referenceTo>Food_Item__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Food_Order__c</fullName>
        <label>Food Order</label>
        <referenceTo>Food_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Price of Individual Line Item</description>
        <label>Price</label>
        <referenceTo>PriceBook__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>The quantity of the food item ordered.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the ordered item.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picked Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Table_Number__c</fullName>
        <description>Required for PushTopics</description>
        <formula>Food_Order__r.TableNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Table Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>Total Price of the ordered item</description>
        <formula>Price__r.Price__c  *  Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Required for PushTopics</description>
        <formula>IF(ISPICKVAL(  Food_Item__r.Category__c ,&apos;Appetizer&apos;), &apos;Appetizer&apos;,
  IF(ISPICKVAL( Food_Item__r.Category__c ,&apos;Entree&apos;), &apos;Entree&apos;,
    IF(ISPICKVAL( Food_Item__r.Category__c ,&apos;Dessert&apos;), &apos;Dessert&apos;, &apos;Entree&apos;)

        )
    )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/PriceBook__c.object
<CustomObject>
    <fields>
        <fullName>Food_Item__c</fullName>
        <label>Food Item</label>
        <referenceTo>Food_Item__c</referenceTo>
        <relationshipLabel>PriceBooks</relationshipLabel>
        <relationshipName>PriceBooks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>PriceBook</label>
    <nameField>
        <label>PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PriceBooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RestaurantManagement/src/classes/BillNew.cls
global with sharing class BillNew{

    //public String foodOrderId = 'a0537000000RI9b';
    public String foodOrderId = ApexPages.currentPage().getParameters().get('orderId');
    public String selLocation=ApexPages.currentPage().getParameters().get('reqlocation');
    public String tableNumber=ApexPages.currentPage().getParameters().get('tableid');
    public Decimal tableNo= Decimal.valueOf(tableNumber);
    
    public String SelectedFQ;
    public String SelectedService;
    public String SelectedOAE;
    public String likes;
    public String unlikes;
    public String tip;
  
    public String getSelectedFQ() {
        return SelectedFQ;
    }
     
    public void setSelectedFQ(String recType) {
        this.SelectedFQ= recType;
    }

     public String gettip() {
        return tip;
    }
     
    public void settip(String recType) {
        this.tip= recType;
    }    
    
    public String getSelectedService() {
        return SelectedService;
    }
     
    public void setSelectedService (String recType) {
        this.SelectedService= recType;
    }
    
    public String getSelectedOAE () {
        return SelectedOAE;
    }
     
    public void setSelectedOAE (String recType) {
        this.SelectedOAE = recType;
    }
    
    
    public String getlikes() {
        System.debug('Likes: '+likes);
        return likes;
    }
     
    public void setlikes(String recType) {
        this.likes= recType;
    }
    
    public String getunlikes() {
        return unlikes;
    }
     
    public void setunlikes(String recType) {
        this.unlikes= recType;
    }
     
    
    public BillNew(){  }
    public List<DisplayCart> orderItemsList;
 
    public static final String PAID = 'Paid';
    
    Food_Order__c fo = getFoodOrder();
    
    public Food_Order__c getFoodOrder(){
    return [SELECT f.Price__c, f.Tax__c, f.TotalPrice__c, f.FinalPrice__c,f.PriceEstimate__c, f.TaxEstimate__c, f.TotalPriceEstimate__c, f.TableNumber__c, f.SystemModstamp, 
                        f.Status__c, f.OrderId__c, f.OrderDateTime__c,
                        f.Name, f.LastViewedDate, f.LastReferencedDate, 
                        f.LastModifiedDate, f.LastModifiedById, f.IsDeleted, f.Id, 
                        f.DeliveryTime__c, f.CreatedDate, f.CreatedById 
                        From Food_Order__c f 
                        where f.id=:foodOrderId];
    }
                            
    public BillNew(ApexPages.StandardController controller) {}
    public BillNew(ApexPages.StandardSetController controller) {}  
  
    //Method to get the billed order items
    public List<DisplayCart> getOrderItemsList() {     
        orderItemsList = new List<DisplayCart>();
        if(orderItemsList == null){
            orderItemsList = new List<DisplayCart>();
        }
        else{
            orderItemsList.clear();    
        }
        
        Map<Id, DisplayCart> itemMap = new Map<Id, DisplayCart>(); 
            
        for(Order_Item__c item : [Select o.Type__c, o.Total_Price__c, o.Table_Number__c, 
                                    o.SystemModstamp, o.Status__c, o.Quantity__c, o.Price__c, 
                                    o.Name, o.LastViewedDate, o.LastReferencedDate, o.LastModifiedDate, 
                                    o.LastModifiedById, o.IsDeleted, o.Id, o.Food_Order__c, 
                                    o.Food_Item__c, o.CreatedDate, o.CreatedById, o.Tax__c 
                                    From Order_Item__c o
                                    where o.Food_order__c=:fo.id and o.Delete_Status__c <> 'Yes'
                                    order by o.Status__c]){
            if(item.Status__c != 'New'){
                    DisplayCart displayCart = new DisplayCart(item);
                    System.debug('Map-----------------------------------');
                    System.debug(itemMap);
                    System.debug('Cart-----------------------------------');
                    System.debug(displayCart);
                    System.debug('-----------------------------------');
                    if(itemMap.containsKey(displayCart.foodItemId)){
                        DisplayCart cart = itemMap.get(displayCart.foodItemId);
                        Decimal quantity = cart.quantity;
                        quantity += item.Quantity__c;
                        cart.quantity = quantity;
                        cart.totalPrice += item.Total_Price__c;
                        System.debug('Updated Cart-----------------------------------');
                        System.debug(cart);
                        itemMap.put(cart.foodItemId, cart);
                        System.debug('Inside****');

                    }
                    else{                        
                       itemMap.put(displayCart.foodItemId, displayCart);
                       System.debug('Else****');
                    }
                }
        }
        //fo = getFoodOrder();
        for(DisplayCart displayCart: itemMap .values()){
            orderItemsList.add(displayCart);
            
           
            }
        
        return orderItemsList;
    }
    
    public void inserttip()
    {
         Food_Order__c foodOrder = [SELECT status__c, TotalPrice__c, FinalPrice__c,TableNumber__c, Tax__c, Name FROM Food_Order__c WHERE ID=:foodOrderId];
         if(String.isBlank(tip))
         { System.Debug('tip'+'NULL');
             foodOrder.Tip__c=0;}
        else{
         foodOrder.Tip__c =Decimal.valueOf(tip);}
         update foodOrder;
         System.Debug('tip'+tip);
         System.debug('price and tip'+foodOrder.FinalPrice__c);
    }
    
     public void insertfeedback()
    {
    Feedback__c fb = new Feedback__c();
    fb.Food_Quality__c=SelectedFQ;
    fb.Overall_Experience__c=SelectedOAE;
    fb.Service__c=SelectedService;
    fb.What_I_liked__c=likes;
    fb.What_must_have_been_there__c=unlikes;
    insert fb;
    }
    
    /*public static String getRestoId(){
       User u  = [SELECT Restaurant_Id__c
                  FROM   User
                  WHERE  Id = :UserInfo.getUserId()];
           
       String rid = u.Restaurant_Id__c;
       
       return rid;
    }*/
    
     public void paidStatusUpdate(){
         Food_Order__c foodOrder = [SELECT status__c, TotalPrice__c, TableNumber__c, Tax__c, Name FROM Food_Order__c WHERE ID=:foodOrderId];
         foodOrder.status__c = PAID;
         update foodOrder;

        Restaurant__c resto = [SELECT Id
                               FROM   Restaurant__c
                               WHERE  Restaurant_Id__c = :selLocation];
        
         Id resto_id = resto.id;
         
         
         Bill__c bill = new Bill__c();  
         bill.TableNumber__c = foodOrder.TableNumber__c;
         bill.Price__c = foodOrder.TotalPrice__c;
         bill.Tax__c = foodOrder.Tax__c;
         bill.Restaurant_ID__c = resto_id ;
         insert bill;
         
          for(DisplayCart displayCart: orderItemsList){
            
            BIll_Item__c billItem= new BIll_Item__c();
            billItem.Name = displayCart.Name;
            billItem.Quantity__c = displayCart.quantity;
            billItem.TotalPrice__c = displayCart.totalPrice;
            billItem.Bill__c = bill.Id;
//            billItem.Tax__c = 3.4// TODO;
            insert billItem;   
            
            PriceBook__c priceBook = [SELECT NoItemsOrdered__c FROM PriceBook__c WHERE ID=:displayCart.priceBook];
            priceBook.NoItemsOrdered__c += 1;
            update priceBook;  
                      
       }     
       
     }
     
     public PageReference finish(){
         PageReference pageRef = Page.Menu_Demo_Copy;
         pageRef.getParameters().put('reqlocation', selLocation);
         pageRef.getParameters().put('tableid', tableNumber);
         pageRef.setRedirect(true);
         return pageRef;
     }

     public PageReference backToCart(){
         PageReference pageRef = Page.Menu_Demo_Copy;
         pageRef.getParameters().put('reqlocation', selLocation);
         pageRef.getParameters().put('tableid', tableNumber);
         pageRef.setRedirect(true);
         return pageRef;
     }
         

    public PageReference rerenderPage() {
        return null;
    }
   


}