RestaurantManagement/src/objects/Category_Level_1__c.object
<CustomObject>
    <description>Defines first level food category in restaurants.</description>
    <label>Category Level-1</label>
    <nameField>
        <label>Category Level-1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category Level-1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Category_Level_2__c.object
<CustomObject>
    <fields>
        <fullName>CategoryFirstLevel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category Level-1</label>
        <referenceTo>Category_Level_1__c</referenceTo>
        <relationshipLabel>Category Level-2</relationshipLabel>
        <relationshipName>Category_Level_2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category Level-2</label>
    <nameField>
        <label>Category Level-2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category Level-2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Food_Order__c.object
<CustomObject>
    <fields>
        <fullName>DeliveryTime__c</fullName>
        <label>Delivery Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrderDateTime__c</fullName>
        <label>Order Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OrderId__c</fullName>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TableNumber__c</fullName>
        <label>Table Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <description>This field will contain the summation of the total price of all the order items which have status accepted and forward in this order, so that the customer is charged for the accepted order items only.</description>
        <inlineHelpText>This is Bill Amount to charge Customer.</inlineHelpText>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Food Order</label>
    <nameField>
        <label>Food Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Restaurant__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Branch</description>
        <inlineHelpText>Branch</inlineHelpText>
        <label>Branch</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>City</inlineHelpText>
        <label>City</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <inlineHelpText>Country where the restaurant is located</inlineHelpText>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabo Verde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <description>Name of Restaurant Manager</description>
        <inlineHelpText>Name of Restaurant Manager</inlineHelpText>
        <label>Manager</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Restaurant_ID__c</fullName>
        <description>Restaurant ID</description>
        <displayFormat>R-{0000}</displayFormat>
        <inlineHelpText>Restaurant ID</inlineHelpText>
        <label>Restaurant ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State</description>
        <inlineHelpText>State</inlineHelpText>
        <label>State</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Street Address</description>
        <label>Street Address</label>
        <length>70</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Zip</description>
        <inlineHelpText>Zip</inlineHelpText>
        <label>Zip</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Restaurant</label>
    <nameField>
        <label>Restaurant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Table__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <description>Locations where restos are located</description>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>California</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newyork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ohio</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>No_of_seats__c</fullName>
        <label>No of seats</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of table in resto- acc. to location</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleaning</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Table_Number__c</fullName>
        <label>Table Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Table</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/classes/MenuItemListControllerTest.cls
@isTest
public class MenuItemListControllerTest{
	
	static Id tableId;
	static String restaurantId;
	static Id categoryLevel1Id;
	static Id categoryLevel2Id;
	static Restaurant__c restaurantObject;
	static Table__c tableObject;
	
	static  void setupdata(){
		restaurantObject = new Restaurant__c();
		restaurantObject.Branch__c='ABC';
		restaurantObject.City__c='NY';
		restaurantObject.Country__c='USA';
		restaurantObject.Name = 'Restaurant1';
		restaurantObject.State__c='Ohio';
		
		restaurantObject.Manager__c='ABC';
		restaurantObject.Street_Address__c='Manhanttan';
		restaurantObject.Zip__c='12345';
		
		insert restaurantObject;
		restaurantId = restaurantObject.id;
		system.debug('Restaurant Id = '+restaurantObject.id);
		system.debug('restaurantObject.Restaurant_ID__c >>'+restaurantObject.Restaurant_ID__c);
		
		tableObject = new Table__c();
		tableObject.No_of_seats__c = 10;
		tableObject.Restaurant_Branch__c = restaurantObject.id;
		tableObject.Status__c ='Ready';
		tableObject.Table_Number__c = '2';
		tableObject.Waiter__c='waiter';
		insert tableObject;
		tableId = tableObject.id ;
		system.debug('tableObject Id >>>>>>>>>> '+tableId);
		
		ApexPages.currentPage().getParameters().put('reqlocation',restaurantObject.Restaurant_ID__c);
		ApexPages.currentPage().getParameters().put('tableid',tableObject.Table_Number__c);
		
		Category_Level_1__c categoryLevel1Object = new Category_Level_1__c();
		categoryLevel1Object.Name ='Sea Food';
		insert categoryLevel1Object;
		categoryLevel1Id = categoryLevel1Object.id ;
		
		Category_Level_2__c categoryLevel2Object = new Category_Level_2__c();
		categoryLevel2Object.CategoryFirstLevel__c = categoryLevel1Id;
	
		categoryLevel2Object.Name='Fish';
		
		insert categoryLevel2Object;
		categoryLevel2Id = categoryLevel2Object.Id;
	}
	
	static testMethod void testMenuItemListControllerTestConstructor(){
		setupdata();
		Test.startTest();
		MenuItemListController MenuItemListControllerObject = new MenuItemListController();
		//Zero Argument Constructor	
		MenuItemListController MenuItemListControllerObject1 = new MenuItemListController(restaurantObject.Restaurant_ID__c, tableObject.Table_Number__c);
		// Parameterized Constuctor
		
		Test.stopTest();
	}
	
	/*
	static void setupDataForFoodOrder(){
		setupdata();
		
		 List<Food_Order__c> existingOrder = [Select f.TotalPrice__c, f.TableNumber__c, f.SystemModstamp, 
            f.Status__c,  f.OrderId__c, f.OrderDateTime__c, f.Name, f.Location__c, f.Restaurant_Branch__r.Restaurant_ID__c, 
            f.LastReferencedDate, f.LastModifiedDate, f.LastModifiedById, 
            f.IsDeleted, f.Id, f.DeliveryTime__c, f.CreatedDate, f.CreatedById From Food_Order__c f
                                     where f.TableNumber__c=:tableNo and f.Status__c != 'Paid' and f.Restaurant_Branch__r.Restaurant_ID__c=:selLocation];
		
		
		Food_Order__c foodOrderObject = new Food_Order__c();
		foodOrderObject.TotalPrice__c = 10.20;
		foodOrderObject.TableNumber__c = '2';
		foodOrderObject.SystemModstamp ='8/21/2015';
		foodOrderObject.Status__c='New';
		foodOrderObject.OrderDateTime__c ='8/13/2015 10:21 AM';
		foodOrderObject.Name ='foodORder';
		foodOrderObject.Location__c='Pune';
		foodOrderObject.Restaurant_Branch__c = restaurantId;
		foodOrderObject.LastReferencedDate = '8/13/2015 10:21 AM';
		foodOrderObject.LastModifiedDate = '8/27/2015';
		
		
		
		
	}
	*/
	
	
	/*
	static testMethod void testGetFoodOrder(){
		
	}*/
	
	
}