RestaurantManagement/src/objects/Food_Item__c.object
<CustomObject>
    <label>Food Item</label>
    <nameField>
        <label>Food Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Food_Order__c.object
<CustomObject>
    <label>Food Order</label>
    <nameField>
        <label>Food Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Order_Item__c.object
<CustomObject>
    <description>The food items ordered by the customer.</description>
    <fields>
        <fullName>Food_Item__c</fullName>
        <description>The food item ordered</description>
        <label>Food Item</label>
        <referenceTo>Food_Item__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Food_Order__c</fullName>
        <label>Food Order</label>
        <referenceTo>Food_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Table_Number__c</fullName>
        <description>Required for PushTopics</description>
        <formula>Food_Order__r.TableNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Table Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/PriceBook__c.object
<CustomObject>
    <fields>
        <fullName>Food_Item__c</fullName>
        <label>Food Item</label>
        <referenceTo>Food_Item__c</referenceTo>
        <relationshipLabel>PriceBooks</relationshipLabel>
        <relationshipName>PriceBooks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PriceBook</label>
    <nameField>
        <label>PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PriceBooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Restaurant__c.object
<CustomObject>
    <label>Restaurant</label>
    <nameField>
        <label>Restaurant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Table__c.object
<CustomObject>
    <fields>
        <fullName>Table_Number__c</fullName>
        <label>Table Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Table</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/classes/Resto_Utility_Chef.cls
@isTest(seeAllData=true)
public class Resto_Utility_Chef {
 

 static testmethod void CreateChef(){
      ChefListController chef= new ChefListController();
      Restaurant__c resto = TestDataFactory.createRestaurant();
      Table__c t = TestDataFactory.createTable(resto);
      Food_Item__c food_item = TestDataFactory.createFoodItem(resto);
      PriceBook__c pbook = TestDataFactory.createPriceBook(resto, food_item);
      Food_Order__c f_order = TestDataFactory.createFoodOrder(resto, Decimal.valueOf(t.Table_Number__c), food_item, pbook);
      Order_Item__c o_item = TestDataFactory.createOrderitem(resto, f_order, food_item, pbook);
      List<PriceBook__c> price = new List<PriceBook__c>();
      price.add(pbook);
      
      Test.startTest();
       
	  Database.SaveResult result1 = Database.insert(resto, false);
      Database.SaveResult result2 = Database.insert(food_item, false);
      Database.SaveResult result3 = Database.insert(pbook, false);
      Database.SaveResult result4 = Database.insert(f_order, false);
      Database.SaveResult result5 = Database.insert(o_item, false);
     
      String ready_id = ChefListController.itemReadyUpdate('a0137000000N1YcAAK');
      System.assertEquals('a0137000000N1YcAAK', ready_id);
 
      String accept_id = ChefListController.itemAcceptUpdate('a0137000000N1YcAAK','a0537000000RI9bAAG');
      System.assertEquals('success', accept_id);
     
      String s = ChefListController.getRestoId();
      System.assertEquals('R-0000', s);
     
      String br = ChefListController.getRestoBranch();
      System.assertEquals('Sawmill, Columbus, Ohio, 43235', br);
     
      ChefListController.updateNoChefs('2');
      ChefListController.handleRefreshPage();
      chef.getnoofchefs();
     
     chef.getselectedlocation();
      chef.getselectedNoChefs();
      chef.setselectedlocation('R-0000');
      chef.setselectedNoChefs('5');
     
	  Test.stopTest();
    }
}