RestaurantManagement/src/objects/Food_Item__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>The category of dish - Appetizer, Entree or Dessert</description>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Appetizer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Entree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dessert</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Whether the food item should be enabled in the menu or not</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enabled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Disbaled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Food Item</label>
    <nameField>
        <label>Food Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Food_Order__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Food Order</label>
    <nameField>
        <label>Food Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Offers__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Food_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Food Item</label>
        <referenceTo>Food_Item__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <label>Offers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Order_Item__c.object
<CustomObject>
    <description>The food items ordered by the customer.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Vegetarian, Non-Vegetarian or Vegan</description>
        <label>Diet Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Food_Item__c</fullName>
        <description>The food item ordered</description>
        <label>Food Item</label>
        <referenceTo>Food_Item__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the ordered item.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picked Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Table_Number__c</fullName>
        <description>Required for PushTopics</description>
        <formula>Food_Order__r.TableNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Table Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/PriceBook__c.object
<CustomObject>
    <fields>
        <fullName>Food_Item__c</fullName>
        <label>Food Item</label>
        <referenceTo>Food_Item__c</referenceTo>
        <relationshipLabel>PriceBooks</relationshipLabel>
        <relationshipName>PriceBooks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PriceBook</label>
    <nameField>
        <label>PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PriceBooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Restaurant__c.object
<CustomObject>
    <fields>
        <fullName>Apartment_Suite__c</fullName>
        <description>Apartment Number</description>
        <inlineHelpText>Apartment Number</inlineHelpText>
        <label>Apartment/Suite</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Branch</description>
        <inlineHelpText>Branch</inlineHelpText>
        <label>Branch</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>City</inlineHelpText>
        <label>City</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <inlineHelpText>Country where the restaurant is located</inlineHelpText>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabo Verde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email</description>
        <inlineHelpText>Email</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <description>Name of Restaurant Manager</description>
        <inlineHelpText>Name of Restaurant Manager</inlineHelpText>
        <label>Manager</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone Number</description>
        <inlineHelpText>Phone Number</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State</description>
        <inlineHelpText>State</inlineHelpText>
        <label>State</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Street Address</description>
        <label>Street Address</label>
        <length>70</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Zip</description>
        <inlineHelpText>Zip</inlineHelpText>
        <label>Zip</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Restaurant</label>
    <nameField>
        <label>Restaurant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Table__c.object
<CustomObject>
    <fields>
        <fullName>No_of_seats__c</fullName>
        <label>No of seats</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of table in resto- acc. to location</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleaning</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Table_Number__c</fullName>
        <label>Table Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Table</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
    public static Restaurant__c createRestaurant(){

        Restaurant__c resto = new Restaurant__c();
        resto.Name= 'Chipotle';
        resto.Apartment_Suite__c='125';
        resto.Branch__c='Tuttle';
        resto.City__c='Dublin';
        resto.Country__c='United States';
        resto.Email__c='chipotle@chipotle.com';
        resto.Manager__c='Lannister';
        resto.Phone__c='8888888888';
        resto.State__c='Ohio';
        resto.Street_Address__c='Tuttle Crossing Blvd';
        resto.Zip__c='99999';

        
        return resto;

    }
    
    public static Table__c createTable(Restaurant__c resto){
  
        Table__c table = new Table__c(No_of_seats__c = 5,
                                     Restaurant_Branch__c = resto.Id,
                                     Status__c='Ready',
                                     Table_Number__c='3',
                                     Waiter__c = 'Waiter'); 
        
        return table;

    }
    
    public static Food_Item__c createFoodItem(Restaurant__c resto){
        Food_Item__c item= new Food_Item__c(Calories__c=100,
                                            status__c = 'enabled',
                                            Category__c='Appetizer',
                                            Description__c='Test Food Item',
                                            Type__c='Vegan',
                                            Name='Test',
                                            Special__c=True,
                                            Prep_Time__c = 20,
                                            Spice_level__c = 'Medium');
        
        createOffer(item);
        createPriceBook(resto, item);
        
         return item;
    }
    
    public static Food_Order__c createFoodOrder(Restaurant__c resto, Decimal table_no, Food_Item__c food_item, 
                                                PriceBook__c pbook){                                        
        Food_Order__c forder = new Food_Order__c(Name = 'Test Food Order',
                                                Restaurant_Branch__c=resto.Id,
                                                TableNumber__c=table_no,
                                                Status__c = 'New');
        return forder;
    }
    public static Order_Item__c createOrderitem(Restaurant__c resto, Food_Order__c food_order, Food_Item__c food_item,
                                                PriceBook__c pbook){                                          
        Order_Item__c orderitem= new Order_Item__c(Name ='Test Order Item',
                                                    Category__c='Vegan',
                                                    Price__c = pbook.Id,
                                                    Food_Item__c = food_item.Id,
                                                    Food_Order__c= food_order.Id,
                                                    Quantity__c=2,
                                                    Restaurant_Id__c= resto.Restaurant_Id__c,
                                                    Status__c= 'New');

        return orderitem;
    }
    
    public static Chef__c createChef(Restaurant__c resto){
        Chef__c chef = new Chef__c(Total_Chefs__c=5,
                                   Restaurant_Id__c= resto.Id);
        return chef;
    }
    
    public static PriceBook__c createPriceBook(Restaurant__c resto, Food_Item__c fitem){
        PriceBook__c pbook = new PriceBook__c (Name = 'Test Price Book',
                                               Price__c=6,
                                               Food_Item__c= fitem.Id,
                                               Restaurant_Branch__c= resto.Id);

        return pbook;
    }
    
    public static RawMaterial__c  createRawMaterial(Restaurant__c resto){
        RawMaterial__c material = new RawMaterial__c();
        material.Name ='Test Raw Material';
        //material.Name__c='Test Raw Material';
        material.Restaurant__c= resto.Id;
        material.threshold__c=4;
        material.Used_till_now__c=4;
        material.Used__c=2;
        
        insert material;
        createPurchase(material);
        
        return material;
    }
    
    public static Purchase__c createPurchase(RawMaterial__c rawmat){
        Purchase__c purchase= new Purchase__c();
        purchase.Price__c=20;
        purchase.Quantity__c=12;
        purchase.RawMaterial__c= rawmat.Id;
        purchase.Date_of_Purchase__c=System.today();
        insert purchase;
        return purchase;
    }
    
    public static Offers__c createOffer(Food_Item__c fitem){
        Offers__c offer = new Offers__c();
        offer.Description__c='Discount';
        offer.Discount__c=10;
        offer.Food_Item__c= fitem.Id;
        
        insert offer;
        return offer;
    }
}