RestaurantManagement/src/objects/Food_Order__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <description>This will contain the order price i.e. the summation of the prices of all the items in the order.</description>
        <inlineHelpText>Order items price summation.</inlineHelpText>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Food Order</label>
    <nameField>
        <label>Food Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Order_Item__c.object
<CustomObject>
    <description>The food items ordered by the customer.</description>
    <fields>
        <fullName>Food_Item_Name__c</fullName>
        <description>Required for PushTopics</description>
        <formula>Food_Item__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Food Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Food_Order__c</fullName>
        <label>Food Order</label>
        <referenceTo>Food_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Price of Individual Line Item</description>
        <label>Price</label>
        <referenceTo>PriceBook__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>The quantity of the food item ordered.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the ordered item.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picked Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Table_Number__c</fullName>
        <description>Required for PushTopics</description>
        <formula>Food_Order__r.TableNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Table Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>Total Price of the ordered item</description>
        <formula>Price__r.Price__c  *  Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RestaurantManagement/src/classes/WaiterListController.cls
global class WaiterListController{
    
    public static final String DELIVERED = 'Delivered';
    public static final String PICKED_UP = 'Picked Up'; 
    
    @RemoteAction
    WebService static void updateOrderPickUp(String orderItemName,Id foodOrderId){
        Order_Item__c orderItem = [SELECT status__c FROM Order_Item__c WHERE Name= :orderItemName];
        orderItem.status__c = PICKED_UP;
        update orderItem;
        
        boolean isOrderDelivered = true;
        Food_Order__c foodOrder = [SELECT status__c FROM Food_Order__c WHERE ID= :orderItem.Food_Order__r.ID];
        List<Order_Item__c> orderItemList = [SELECT Food_Item_Name__c,Price__c,Quantity__c,Table_Number__c,Total_Price__c,status__c FROM Order_Item__c WHERE food_order__r.ID= :foodOrder.ID];
        for(Order_Item__c orderItemVal: orderItemList){
            if(orderItemVal.status__c <> PICKED_UP){
                isOrderDelivered = false;
                break;
            }
        }
        if(isOrderDelivered){
            foodOrder.status__c = DELIVERED;
            update foodOrder;
        }
    }
}