RestaurantManagement/src/objects/Food_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Food Item</label>
    <nameField>
        <label>Food Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Offers__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Food_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Food Item</label>
        <referenceTo>Food_Item__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <label>Offers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/PriceBook__c.object
<CustomObject>
    <fields>
        <fullName>Food_Item__c</fullName>
        <label>Food Item</label>
        <referenceTo>Food_Item__c</referenceTo>
        <relationshipLabel>PriceBooks</relationshipLabel>
        <relationshipName>PriceBooks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PriceBook</label>
    <nameField>
        <label>PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PriceBooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RestaurantManagement/src/classes/DisplayOffer.cls
global class DisplayOffer{
        private Offers__c availableOffers;
        private Decimal pricetag;
        private String imgurl;
        private PriceBook__c book;
        
        
        public Integer getCount(){
            return 3;
        }
        
        public DisplayOffer(Offers__c offer){
            this.availableOffers= offer;
            
        }

        public String name{
            get{return availableOffers.Food_Item__r.name;}
        }
        
        public Decimal discount{
            get{return availableOffers.discount__c;}
        }        
        public String description{
            get{return availableOffers.Description__c;}
        }
        
       
        
}