RestaurantManagement/src/objects/Food_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Diet__c</fullName>
        <label>Diet</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Prep_Time__c</fullName>
        <label>Preparation Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Whether the food item should be enabled in the menu or not</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enabled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Disbaled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of food - Veg, Non-Veg or Vegan</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Vegetarian</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Vegetarian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vegan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Food Item</label>
    <nameField>
        <label>Food Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/PriceBook__c.object
<CustomObject>
    <fields>
        <fullName>Food_Item__c</fullName>
        <label>Food Item</label>
        <referenceTo>Food_Item__c</referenceTo>
        <relationshipLabel>PriceBooks</relationshipLabel>
        <relationshipName>PriceBooks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PriceBook</label>
    <nameField>
        <label>PriceBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PriceBooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RestaurantManagement/src/classes/ItemController.cls
public class ItemController{
        private Food_Item__c item;
        private Decimal pricetag;
        private String imgurl;
        private PriceBook__c book;
        private Decimal numOfTimesOrdered;
        private String itemName;    
        
        public String getItemName(){
            return this.itemName;
        }
        
   public ItemController(){
           
        }
       
       public class Item{ 
        
         private Food_Item__c item;
        private Decimal pricetag;
        private String imgurl;
        private PriceBook__c book;
        private Decimal numOfTimesOrdered;
        
        
                
                public Decimal price{
            get{return this.pricetag;}
        }        
        public String description{
            get{return item.Description__c;}
        }
        
        public Decimal preptime{
            get{return item.Prep_Time__c;}
        }
        
      public Decimal calories{
            get{return item.Calories__c;}
        }
    
        public String status{
            get{return item.Status__c;}
        }
        
        public boolean isSpecial{
            get{return item.Special__c;}
        }
        public String typ{
            get{return item.Type__c;}
        }
        
        public Boolean starredItem{
            get;
            set;
        }
        }
        
        public String getimgurl(){
           imgurl = item.Item_Image__c+'';
           Integer st_index = imgurl.IndexOf('src');
           Integer end_index = imgurl.lastIndexOf('\"');
           
           Integer len = end_index - (st_index+5);
           imgurl = imgurl.mid(st_index+5,len).replace('&amp;','&');
           return imgurl; 
       }
        
        // public Object diet{
          //  get{return item.Diet__c;}
        //}
     
        public Decimal getNumOfTimesOrdered(){
            return this.numOfTimesOrdered;
        }
     
        public Integer compareTo(Object o){
            return (Integer)(((DisplayMenuItems)o).getNumOfTimesOrdered() - this.getNumOfTimesOrdered());
        }
     
        
    }