RestaurantManagement/src/objects/Restaurant__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Branch</description>
        <inlineHelpText>Branch</inlineHelpText>
        <label>Branch</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>City</inlineHelpText>
        <label>City</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <inlineHelpText>Country where the restaurant is located</inlineHelpText>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabo Verde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <description>Name of Restaurant Manager</description>
        <inlineHelpText>Name of Restaurant Manager</inlineHelpText>
        <label>Manager</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Restaurant_ID__c</fullName>
        <description>Restaurant ID</description>
        <displayFormat>R-{0000}</displayFormat>
        <inlineHelpText>Restaurant ID</inlineHelpText>
        <label>Restaurant ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State</description>
        <inlineHelpText>State</inlineHelpText>
        <label>State</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Street Address</description>
        <label>Street Address</label>
        <length>70</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Zip</description>
        <inlineHelpText>Zip</inlineHelpText>
        <label>Zip</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Restaurant</label>
    <nameField>
        <label>Restaurant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/objects/Table__c.object
<CustomObject>
    <fields>
        <fullName>No_of_seats__c</fullName>
        <label>No of seats</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of table in resto- acc. to location</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleaning</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Table_Number__c</fullName>
        <label>Table Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Table</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RestaurantManagement/src/classes/tablecontrollerTest.cls
@isTest
public class tablecontrollerTest {
	
	static Id tableId;
	static String restaurantId;
	static  void setupdata(){
		Restaurant__c restaurantObject = new Restaurant__c();
		restaurantObject.Branch__c='ABC';
		restaurantObject.City__c='NY';
		restaurantObject.Country__c='USA';
		restaurantObject.Name = 'Restaurant1';
		restaurantObject.State__c='Ohio';
		
		restaurantObject.Manager__c='ABC';
		restaurantObject.Street_Address__c='Manhanttan';
		restaurantObject.Zip__c='12345';
		
		insert restaurantObject;
		system.debug('Restaurant Id = '+restaurantObject.id);
		system.debug('restaurantObject.Restaurant_ID__c >>'+restaurantObject.Restaurant_ID__c);
		
		Table__c tableObject = new Table__c();
		tableObject.No_of_seats__c = 10;
		tableObject.Restaurant_Branch__c = restaurantObject.id;
		tableObject.Status__c ='Ready';
		tableObject.Table_Number__c = '2';
		tableObject.Waiter__c='waiter';
		insert tableObject;
		tableId = tableObject.id ;
		system.debug('tableObject Id >>>>>>>>>> '+tableId);
	}
	
	static testMethod void testGetRestoId(){
		setupdata();
		Test.startTest(); 
		restaurantId = tablecontroller.getRestoId();
		system.debug('Restaurant Id >>>>>>>>>>>> '+restaurantId);
		Test.stopTest();
		System.assertNotEquals(restaurantId, null);
	}
	
	static testMethod void testUpdatestatus(){
		setupdata();
		Test.startTest(); 
		ApexPages.currentPage().getParameters().put('tablename',tableId);
		tablecontroller tablecontrollerobject = new tablecontroller();
		tablecontrollerobject.updatestatus();
		Test.stopTest();
	}
	
	static testMethod void testGettables(){
		setupdata();
		Test.startTest(); 
		tablecontroller tablecontrollerobject = new tablecontroller();
		tablecontroller.uid = restaurantId;
		tablecontrollerobject.gettables();
		Test.stopTest();
	}
}